# Generated by Django 4.2 on 2023-05-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_hospital_ambulance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='contact',
            field=models.CharField(max_length=35),
        ),
    ]
