# Generated by Django 4.1.7 on 2023-04-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_hospital_ambulance'),
        ('doctors', '0003_remove_department_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.city'),
        ),
    ]
