# Generated by Django 4.2 on 2023-05-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='availability_on',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=40),
        ),
    ]
